### PR TITLE
Add UUIDUtils

### PR DESCRIPTION
**Pull request by Leonardo-DGS**
Added an util to manage UUIDs.

### CODE REVIEW

**Comment by FerusGrim** [comment]
The utilities which have to fetch data over a remote connection should be creating a Promise, imo.

**Comment by FerusGrim** [comment]
Additionally, UUIDUtils#getOnlineUUID and UUIDUtils#getNameHistory should be wrapping their connections/readers in try-with-resource.

If you encounter an exception, you're never closing them and it could cause memory leaks.

**Comment by FerusGrim** [comment]
I've implemented my suggestions and made a PR to your branch so you can pull it into this PR, if you want, and save yourself some time?

https://github.com/Leonardo-DGS/helper/pull/1

**Comment by FerusGrim** [comment]
Here's a very basic usage example:

```java
    private static final Table<UUID, UUID, List<String>> offlineMessages = HashBasedTable.create();

    public static void sendOfflineMessage(ExtendedJavaPlugin plugin, Player player, String recipientName, String message) {
        UUIDUtils.getOnlineUUID(recipientName)
                .thenApplySync(recipientUuid -> {
                    if (recipientUuid == null) {
                        return false;
                    }
                    if (!offlineMessages.contains(recipientUuid, player.getUniqueId())) {
                        offlineMessages.put(recipientUuid, player.getUniqueId(), Lists.newArrayList());
                    }
                    offlineMessages.get(recipientUuid, player.getUniqueId()).add(message);
                    return true;
                }).thenAcceptSync(sent -> {
                    if (sent) {
                        Players.msg(player, "&aMessage sent!");
                    } else {
                        Players.msg(player, "&cFailed to send message!");
                    }
                }).bindWith(plugin);
    }
```

And, of course, if you need it right away:

```java
    public static UUID getOnlineUuidNow(String username) {
        return getOnlineUUID(username).join();
    }
```

**Comment by Leonardo-DGS** [comment]
@FerusGrim thank you!

**Comment by lucko** [comment]
Thanks :)

**Pull request merged**
