### PR TITLE
Update mongo-java-driver version

### PR DESCRIPTION
**Pull request by FerusGrim**

### CODE REVIEW

**Comment by DokanBoy** [comment]
is it work? I cant find mongo-java-driver 4.2.0 on maven central

**Comment by lucko** [comment]
Well spotted! Yeah, it seems `3.12.7` is the latest for the artifact we're using.

Perhaps you meant https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-core ?

If we're bumping to a new major release, probably need to increment the helper-mongo version too.

**Comment by FerusGrim** [comment]
Just testing you guys, of course.

**Comment by DokanBoy** [comment]
@lucko wtf???

**Comment by lucko** [comment]
> @lucko wtf???

hm?

**Comment by DokanBoy** [comment]
> 
> 
> > @lucko wtf???
> 
> hm?

Are you sure it will work? I think it will break the build.

**Comment by FerusGrim** [comment]
@DokanBoy Nope, it still builds fine. You may have missed my sneaky commit to fix the issue.

**Comment by DokanBoy** [comment]
> 
> 
> @DokanBoy Nope, it still builds fine. You may have missed my sneaky commit to fix the issue.

Ooops, sorry.

**Pull request merged**
